name: notey
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: #http
  get_it: #Service Locator
  rename: 2.0.1 #Rename
  lottie: 1.4.2 #Animations
  shimmer: 2.0.0 #Skeleton
  provider: #State Management
  flutter_svg: #Svg
  url_launcher: 6.1.5 #Luncher
  cupertino_icons: 1.0.2 #IOS Icons
  easy_localization: #Localizations
  shared_preferences: #Local Storage
  flutter_screenutil: #Responsive Design
  cached_network_image: #Images
  connectivity_plus: 2.3.7 #Connectivity
  introduction_screen: ^3.0.2
  simple_gradient_text: ^1.2.4
  grouped_list: ^5.1.2
  internet_connection_checker:




dev_dependencies:

  #App Icon

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/translations/
    - assets/icons/Light/
    - assets/animations/disconnected_network.json



  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
